# Generated by Django 5.0.4 on 2024-05-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slideritem",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="slideritem",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
